// src/constants/levels.ts
import type { Level } from '../types/game';

export const LEVELS: Level[] = [
  // === KOLAY SEVİYELER (1-5) ===
  {
    id: 1,
    gridSize: 5,
    playerPos: { x: 0, y: 2 },
    playerDir: 'EAST',
    targetPos: { x: 4, y: 2 },
    obstacles: [],
    collectibles: [],
    maxMoves: 5,
  },
  {
    id: 2,
    gridSize: 5,
    playerPos: { x: 2, y: 0 },
    playerDir: 'SOUTH',
    targetPos: { x: 2, y: 4 },
    obstacles: [],
    collectibles: [],
    maxMoves: 5,
  },
  {
    id: 3,
    gridSize: 5,
    playerPos: { x: 0, y: 0 },
    playerDir: 'EAST',
    targetPos: { x: 2, y: 0 },
    obstacles: [{ x: 1, y: 0 }],
    collectibles: [],
    maxMoves: 8,
  },
  {
    id: 4,
    gridSize: 5,
    playerPos: { x: 0, y: 0 },
    playerDir: 'SOUTH',
    targetPos: { x: 4, y: 4 },
    obstacles: [{ x: 2, y: 2 }],
    collectibles: [],
    maxMoves: 10,
  },
  {
    id: 5,
    gridSize: 5,
    playerPos: { x: 4, y: 0 },
    playerDir: 'WEST',
    targetPos: { x: 0, y: 0 },
    obstacles: [{ x: 2, y: 0 }, { x: 1, y: 0 }],
    collectibles: [],
    maxMoves: 10,
  },

  // === ORTA SEVİYELER (6-10) ===
  {
    id: 6,
    gridSize: 5,
    playerPos: { x: 0, y: 4 },
    playerDir: 'NORTH',
    targetPos: { x: 4, y: 0 },
    obstacles: [{ x: 0, y: 2 }, { x: 2, y: 2 }, { x: 4, y: 2 }],
    collectibles: [],
    maxMoves: 12,
  },
  {
    id: 7,
    gridSize: 5,
    playerPos: { x: 0, y: 0 },
    playerDir: 'EAST',
    targetPos: { x: 4, y: 4 },
    obstacles: [{ x: 1, y: 1 }, { x: 2, y: 1 }, { x: 3, y: 3 }],
    collectibles: [{ x: 2, y: 2 }],
    maxMoves: 15,
  },
  {
    id: 8,
    gridSize: 5,
    playerPos: { x: 4, y: 4 },
    playerDir: 'WEST',
    targetPos: { x: 0, y: 0 },
    obstacles: [{ x: 2, y: 2 }, { x: 2, y: 3 }, { x: 3, y: 2 }],
    collectibles: [],
    maxMoves: 15,
  },
  {
    id: 9,
    gridSize: 6,
    playerPos: { x: 0, y: 3 },
    playerDir: 'EAST',
    targetPos: { x: 5, y: 3 },
    obstacles: [{ x: 2, y: 2 }, { x: 2, y: 3 }, { x: 2, y: 4 }],
    collectibles: [{ x: 1, y: 3 }],
    maxMoves: 12,
  },
  {
    id: 10,
    gridSize: 6,
    playerPos: { x: 0, y: 0 },
    playerDir: 'SOUTH',
    targetPos: { x: 5, y: 5 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 3 }, { x: 4, y: 2 }],
    collectibles: [{ x: 0, y: 5 }, { x: 5, y: 0 }],
    maxMoves: 20,
  },

  // === İLERİ SEVİYELER (11-15) ===
  {
    id: 11,
    gridSize: 6,
    playerPos: { x: 5, y: 5 },
    playerDir: 'NORTH',
    targetPos: { x: 0, y: 0 },
    obstacles: [{ x: 3, y: 3 }, { x: 2, y: 3 }, { x: 3, y: 2 }, { x: 1, y: 4 }],
    collectibles: [{ x: 2, y: 2 }],
    maxMoves: 18,
  },
  {
    id: 12,
    gridSize: 6,
    playerPos: { x: 0, y: 3 },
    playerDir: 'EAST',
    targetPos: { x: 5, y: 2 },
    obstacles: [{ x: 2, y: 1 }, { x: 2, y: 2 }, { x: 2, y: 3 }, { x: 2, y: 4 }, { x: 4, y: 2 }],
    collectibles: [{ x: 3, y: 5 }],
    maxMoves: 20,
  },
  {
    id: 13,
    gridSize: 6,
    playerPos: { x: 5, y: 0 },
    playerDir: 'WEST',
    targetPos: { x: 0, y: 5 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 2, y: 3 }, { x: 3, y: 3 }],
    collectibles: [{ x: 0, y: 0 }, { x: 5, y: 5 }],
    maxMoves: 22,
  },
  {
    id: 14,
    gridSize: 6,
    playerPos: { x: 3, y: 5 },
    playerDir: 'NORTH',
    targetPos: { x: 3, y: 0 },
    obstacles: [{ x: 3, y: 3 }, { x: 2, y: 2 }, { x: 4, y: 2 }, { x: 3, y: 1 }],
    collectibles: [{ x: 1, y: 1 }, { x: 5, y: 1 }],
    maxMoves: 25,
  },
  {
    id: 15,
    gridSize: 7,
    playerPos: { x: 0, y: 0 },
    playerDir: 'EAST',
    targetPos: { x: 6, y: 6 },
    obstacles: [{ x: 3, y: 2 }, { x: 3, y: 3 }, { x: 3, y: 4 }],
    collectibles: [{ x: 3, y: 0 }, { x: 3, y: 6 }],
    maxMoves: 25,
  },

  // === ZOR SEVİYELER (16-20) ===
  {
    id: 16,
    gridSize: 7,
    playerPos: { x: 6, y: 3 },
    playerDir: 'WEST',
    targetPos: { x: 0, y: 3 },
    obstacles: [{ x: 3, y: 2 }, { x: 3, y: 3 }, { x: 3, y: 4 }, { x: 4, y: 1 }, { x: 4, y: 5 }],
    collectibles: [{ x: 5, y: 0 }, { x: 5, y: 6 }],
    maxMoves: 28,
  },
  {
    id: 17,
    gridSize: 7,
    playerPos: { x: 3, y: 6 },
    playerDir: 'NORTH',
    targetPos: { x: 3, y: 0 },
    obstacles: [{ x: 3, y: 4 }, { x: 2, y: 3 }, { x: 4, y: 3 }, { x: 3, y: 2 }, { x: 1, y: 1 }, { x: 5, y: 1 }],
    collectibles: [{ x: 0, y: 3 }, { x: 6, y: 3 }],
    maxMoves: 30,
  },
  {
    id: 18,
    gridSize: 7,
    playerPos: { x: 0, y: 6 },
    playerDir: 'EAST',
    targetPos: { x: 6, y: 0 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 3 }, { x: 4, y: 4 }, { x: 2, y: 4 }, { x: 4, y: 2 }],
    collectibles: [{ x: 0, y: 0 }, { x: 6, y: 6 }, { x: 3, y: 0 }],
    maxMoves: 35,
  },
  {
    id: 19,
    gridSize: 7,
    playerPos: { x: 6, y: 6 },
    playerDir: 'SOUTH',
    targetPos: { x: 0, y: 0 },
    obstacles: [{ x: 3, y: 3 }, { x: 2, y: 3 }, { x: 4, y: 3 }, { x: 3, y: 2 }, { x: 3, y: 4 }, { x: 1, y: 1 }, { x: 5, y: 5 }],
    collectibles: [{ x: 0, y: 6 }, { x: 6, y: 0 }, { x: 3, y: 6 }],
    maxMoves: 38,
  },
  {
    id: 20,
    gridSize: 7,
    playerPos: { x: 3, y: 0 },
    playerDir: 'SOUTH',
    targetPos: { x: 3, y: 6 },
    obstacles: [{ x: 3, y: 2 }, { x: 2, y: 3 }, { x: 4, y: 3 }, { x: 3, y: 4 }, { x: 1, y: 5 }, { x: 5, y: 5 }],
    collectibles: [{ x: 0, y: 0 }, { x: 6, y: 0 }, { x: 0, y: 6 }, { x: 6, y: 6 }],
    maxMoves: 40,
  },

  // === ÇOK ZOR SEVİYELER (21-25) ===
  {
    id: 21,
    gridSize: 8,
    playerPos: { x: 0, y: 4 },
    playerDir: 'EAST',
    targetPos: { x: 7, y: 4 },
    obstacles: [{ x: 2, y: 3 }, { x: 2, y: 4 }, { x: 2, y: 5 }, { x: 5, y: 3 }, { x: 5, y: 4 }, { x: 5, y: 5 }],
    collectibles: [{ x: 3, y: 0 }, { x: 4, y: 7 }],
    maxMoves: 35,
  },
  {
    id: 22,
    gridSize: 8,
    playerPos: { x: 7, y: 7 },
    playerDir: 'WEST',
    targetPos: { x: 0, y: 0 },
    obstacles: [{ x: 3, y: 3 }, { x: 4, y: 3 }, { x: 3, y: 4 }, { x: 4, y: 4 }, { x: 2, y: 5 }, { x: 5, y: 2 }, { x: 1, y: 1 }, { x: 6, y: 6 }],
    collectibles: [{ x: 0, y: 7 }, { x: 7, y: 0 }, { x: 3, y: 7 }],
    maxMoves: 45,
  },
  {
    id: 23,
    gridSize: 8,
    playerPos: { x: 4, y: 0 },
    playerDir: 'SOUTH',
    targetPos: { x: 4, y: 7 },
    obstacles: [{ x: 4, y: 2 }, { x: 3, y: 3 }, { x: 5, y: 3 }, { x: 4, y: 4 }, { x: 2, y: 5 }, { x: 6, y: 5 }],
    collectibles: [{ x: 0, y: 3 }, { x: 7, y: 3 }, { x: 4, y: 6 }],
    maxMoves: 40,
  },
  {
    id: 24,
    gridSize: 8,
    playerPos: { x: 0, y: 0 },
    playerDir: 'EAST',
    targetPos: { x: 7, y: 7 },
    obstacles: [{ x: 3, y: 1 }, { x: 3, y: 2 }, { x: 3, y: 3 }, { x: 5, y: 4 }, { x: 5, y: 5 }, { x: 5, y: 6 }, { x: 1, y: 5 }, { x: 6, y: 2 }],
    collectibles: [{ x: 0, y: 7 }, { x: 7, y: 0 }, { x: 3, y: 5 }, { x: 5, y: 2 }],
    maxMoves: 50,
  },
  {
    id: 25,
    gridSize: 8,
    playerPos: { x: 7, y: 0 },
    playerDir: 'WEST',
    targetPos: { x: 0, y: 7 },
    obstacles: [{ x: 3, y: 3 }, { x: 4, y: 3 }, { x: 3, y: 4 }, { x: 4, y: 4 }, { x: 2, y: 2 }, { x: 5, y: 2 }, { x: 2, y: 5 }, { x: 5, y: 5 }],
    collectibles: [{ x: 3, y: 0 }, { x: 4, y: 0 }, { x: 0, y: 3 }, { x: 7, y: 4 }, { x: 3, y: 7 }],
    maxMoves: 55,
  },

  // === UZMAN SEVİYELER (26-30) ===
  {
    id: 26,
    gridSize: 8,
    playerPos: { x: 4, y: 7 },
    playerDir: 'NORTH',
    targetPos: { x: 4, y: 0 },
    obstacles: [{ x: 4, y: 5 }, { x: 3, y: 4 }, { x: 5, y: 4 }, { x: 2, y: 3 }, { x: 6, y: 3 }, { x: 4, y: 2 }, { x: 1, y: 1 }, { x: 7, y: 1 }],
    collectibles: [{ x: 0, y: 7 }, { x: 7, y: 7 }, { x: 0, y: 0 }, { x: 7, y: 0 }],
    maxMoves: 50,
  },
  {
    id: 27,
    gridSize: 9,
    playerPos: { x: 0, y: 4 },
    playerDir: 'EAST',
    targetPos: { x: 8, y: 4 },
    obstacles: [{ x: 2, y: 3 }, { x: 2, y: 4 }, { x: 2, y: 5 }, { x: 5, y: 2 }, { x: 5, y: 3 }, { x: 5, y: 4 }, { x: 5, y: 5 }, { x: 5, y: 6 }],
    collectibles: [{ x: 3, y: 0 }, { x: 4, y: 8 }, { x: 6, y: 4 }],
    maxMoves: 45,
  },
  {
    id: 28,
    gridSize: 9,
    playerPos: { x: 8, y: 8 },
    playerDir: 'NORTH',
    targetPos: { x: 0, y: 0 },
    obstacles: [{ x: 4, y: 4 }, { x: 3, y: 3 }, { x: 5, y: 3 }, { x: 3, y: 5 }, { x: 5, y: 5 }, { x: 2, y: 2 }, { x: 6, y: 2 }, { x: 2, y: 6 }, { x: 6, y: 6 }, { x: 1, y: 7 }],
    collectibles: [{ x: 0, y: 8 }, { x: 8, y: 0 }, { x: 4, y: 0 }, { x: 4, y: 8 }, { x: 0, y: 4 }],
    maxMoves: 60,
  },
  {
    id: 29,
    gridSize: 9,
    playerPos: { x: 4, y: 0 },
    playerDir: 'SOUTH',
    targetPos: { x: 4, y: 8 },
    obstacles: [{ x: 4, y: 2 }, { x: 3, y: 3 }, { x: 5, y: 3 }, { x: 2, y: 4 }, { x: 6, y: 4 }, { x: 4, y: 5 }, { x: 1, y: 6 }, { x: 7, y: 6 }, { x: 4, y: 7 }],
    collectibles: [{ x: 0, y: 0 }, { x: 8, y: 0 }, { x: 0, y: 4 }, { x: 8, y: 4 }, { x: 0, y: 8 }, { x: 8, y: 8 }],
    maxMoves: 65,
  },
  {
    id: 30,
    gridSize: 9,
    playerPos: { x: 0, y: 0 },
    playerDir: 'EAST',
    targetPos: { x: 8, y: 8 },
    obstacles: [
      { x: 2, y: 1 }, { x: 2, y: 2 }, { x: 2, y: 3 },
      { x: 4, y: 3 }, { x: 4, y: 4 }, { x: 4, y: 5 },
      { x: 6, y: 5 }, { x: 6, y: 6 }, { x: 6, y: 7 },
      { x: 1, y: 5 }, { x: 3, y: 7 }, { x: 7, y: 3 }
    ],
    collectibles: [{ x: 0, y: 8 }, { x: 8, y: 0 }, { x: 4, y: 0 }, { x: 4, y: 8 }, { x: 0, y: 4 }, { x: 8, y: 4 }, { x: 4, y: 4 }],
    maxMoves: 70,
  },
];